name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Build package
        run: |
          python setup.py sdist

      - name: Run unit tests
        run: |
          python -m unittest --verbose

      - name: Publish package to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Create release on Github
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
